### ISSUE TITLE
restarting the pc resets settings

### ISSUE THREAD

**Issue by stad-nico** [roundedcorners/app#25]
The application doesnt save its settings, at least after restarting the pc all the changes are gone. 
I added the .exe to the windows 11 autostart folder, but I have to manually adjust the corner size after each restart.

**Comment by stad-nico** [comment]
Solved it by moving the executable to a permanent location inside a folder, and only pointing to the executable via a link in the autostart folder.

**Comment by nikolaxhristov** [comment]
The `.exe` is the portable version, you'd have to install the `.msi` to persist local storage.
