### ISSUE TITLE
No support for multiple monitors setups.

### ISSUE THREAD

**Issue by lucasCosta0** [roundedcorners/app#37]
The app doesn't support multi screen setups, it works fine on the main screen, but any other screens you might have will not have rounded corners.

**Comment by SpoiledSoul** [comment]
Also the same "issue." Is this perhaps a limitation due to Windows having a primary display?

**Comment by nikolaxhristov** [comment]
@chatcody

**Comment by nikolaxhristov** [comment]
Fixed in https://github.com/roundedcorners/app/releases/tag/v0.0.4

**Comment by SpoiledSoul** [comment]
This sort of fixed the issue for me. The are in fact two screens with rounded corners, but only the top, central two corners are rounded. The rest of the corners are not, however. See the screenshot [here](https://imgur.com/n5aQzFJ). Running Windows 11 (KB5023706).

**Comment by nikolaxhristov** [comment]
What a weird issue @SpoiledSoul. Can I trouble you for a debug session offline. My Dicord is nikolahristov#1833
