### ISSUE TITLE
Doesn't seem to work properly when using display scaling

### ISSUE THREAD

**Issue by robinrai123** [roundedcorners/app#61]
Hi, love the app! It seems however only the top left corner works when using Windows display scaling - I tried both the MSI and the exe, and only saw all corners be rounded when using 100% display scaling. When using 125% the mentioned issue occurs.

Thanks and great work!

Here's the issue at 125%:
![image](https://user-images.githubusercontent.com/61349310/226187766-5c223b6f-1388-4e6a-a03f-a4a728c1d598.png)

And here it is at 100% (requires restarting the app when changing scale):
![image](https://user-images.githubusercontent.com/61349310/226187882-1f5b68a3-ca17-4b02-b0ce-f89d761433c0.png)

**Comment by HuyHung1408** [comment]
I'm facing the same issue, hope this will be fixed soon

**Comment by nikolaxhristov** [comment]
Fixed in https://github.com/roundedcorners/app/releases/tag/v0.0.5

**Comment by HuyHung1408** [comment]
Thanks!
